from langchain_openai import ChatOpenAI
from src.config import settings
from src.retriever import EnterpriseRetriever


# Initialize the LLM used across all agent steps.
# A low temperature is used to keep responses more consistent and less random,
# which is helpful for enterprise document question answering.
llm = ChatOpenAI(
    model=settings.llm_model,
    api_key=settings.openai_api_key,
    temperature=0.1
)


def _format_docs(docs):
    """
    Convert retrieved document chunks into a single text block.

    Why this is needed:
    - The retriever returns a list of matching document chunks.
    - The LLM needs those chunks in a readable prompt format.
    - Including the source name helps the final response stay grounded
      and improves traceability for the user.

    Args:
        docs: List of retrieved document objects from the vector store.

    Returns:
        A formatted string containing source names and chunk text.
    """
    if not docs:
        return "No relevant context found."

    return "\n\n".join(
        [
            f"Source: {d.metadata.get('source', 'Unknown')}\n{d.page_content}"
            for d in docs
        ]
    )


def _planner_step(query: str) -> str:
    """
    Planner agent step.

    Purpose:
    - Interprets the user query before answering.
    - Breaks the question into intent, key topics, and evidence needed.
    - Simulates the 'planning agent' part of the capstone requirement.

    Args:
        query: User's natural language question.

    Returns:
        A short plan generated by the LLM.
    """
    prompt = f"""
You are a query planning agent.
Break this user question into a short retrieval plan.

Question:
{query}

Return:
1. Intent
2. Key topics
3. What evidence to retrieve
"""
    return llm.invoke(prompt).content


def _reasoner_step(query: str, context: str, plan: str) -> str:
    """
    Reasoning agent step.

    Purpose:
    - Uses the retrieval plan and retrieved document content.
    - Produces a grounded answer using only the available context.
    - Prevents the model from answering outside the retrieved evidence.

    Args:
        query: Original user question.
        context: Retrieved document chunks formatted as text.
        plan: Output from the planner step.

    Returns:
        Draft answer generated by the LLM.
    """
    prompt = f"""
You are a reasoning agent in an enterprise RAG system.

User question:
{query}

Retrieval plan:
{plan}

Retrieved context:
{context}

Instructions:
- Answer only from the retrieved context.
- Be concise and accurate.
- If the context is insufficient, say so clearly.
- Include source names when possible.
"""
    return llm.invoke(prompt).content


def _validator_step(query: str, draft_answer: str, context: str) -> str:
    """
    Validator agent step.

    Purpose:
    - Reviews the draft answer for grounding and safety.
    - Checks whether the response is supported by retrieved context.
    - Reduces hallucination by asking the LLM to revise weak or unsupported output.

    Args:
        query: Original user question.
        draft_answer: Initial answer from the reasoning step.
        context: Retrieved context used for answer generation.

    Returns:
        Final validated answer.
    """
    prompt = f"""
You are a validation agent.

Question:
{query}

Draft answer:
{draft_answer}

Retrieved context:
{context}

Validate the draft answer:
- Is it grounded in the context?
- Does it avoid hallucination?
- Does it mention source(s)?
If needed, rewrite the answer to be safer and more accurate.
"""
    return llm.invoke(prompt).content


def run_agentic_pipeline(query: str, retriever: EnterpriseRetriever) -> str:
    """
    Main end-to-end agentic workflow.

    Workflow:
    1. Planner agent analyzes the question.
    2. Retriever fetches the most relevant document chunks from the vector database.
    3. Reasoner agent creates a draft answer using retrieved context.
    4. Validator agent checks and improves the answer before returning it.

    This function represents the capstone's agent-based reasoning flow
    built on top of Retrieval-Augmented Generation (RAG). [file:24]

    Args:
        query: User's question.
        retriever: EnterpriseRetriever instance connected to the vector store.

    Returns:
        Final validated response.
    """
    # Step 1: Create a retrieval plan from the user query
    plan = _planner_step(query)

    # Step 2: Fetch the most relevant document chunks using semantic search
    docs = retriever.get_relevant_documents(query)

    # Step 3: Convert retrieved chunks into prompt-friendly text
    context = _format_docs(docs)

    # Step 4: Generate a grounded draft answer from retrieved context
    draft = _reasoner_step(query, context, plan)

    # Step 5: Validate and refine the draft answer
    final_answer = _validator_step(query, draft, context)

    return final_answer
